[package]
name = "pda-local"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program = "2.0.10"
borsh = "1.5.1"
thiserror = "1.0.63"

[lib]
crate-type = ["cdylib", "lib"]
